stages:
  - release

variables:
  PACKAGE_NAME: '@jeanmc/finnhub-sdk'
  YARN_ENABLE_IMMUTABLE_INSTALLS: 'false'

release:
  stage: release
  image: node:20
  interruptible: true
  services:
    - name: swaggerapi/swagger-converter:v1.0.4
      alias: swagger-converter
  variables:
    AUTOREST_OUTPUT_FOLDER: ./packages/generated
    PACKAGE_PUBLISH: 'true'
    SWAGGER_CONVERT_API: http://swagger-converter:8080/api/convert
    SWAGGER_FILE_URL: https://finnhub.io/static/swagger.json
  before_script:
    - apt-get update && apt-get install -y curl jq
    - npm install --location=global autorest semver
  script:
    - ./scripts/generate.sh
    # send out notification email
    - |
      node $MAILERSEND_BUILD_PACKAGE_RELEASE_NOTIFICATION_PAYLOAD | curl -X POST $MAILERSEND_API_URL \
        -H 'Content-Type: application/json' \
        -H 'X-Requested-With: XMLHttpRequest' \
        -H "Authorization: Bearer $MAILERSEND_API_TOKEN" \
        -d @-
