include:
  - project: 'jeanmc/ci-template'
    file: '/job-templates/email-notification.yml'

stages:
  - release

variables:
  PACKAGE_NAME: '@jeanmc/finnhub-sdk'
  YARN_ENABLE_IMMUTABLE_INSTALLS: 'false'

release:
  stage: release
  image: node:20
  interruptible: true
  except:
    - .email-notification
  services:
    - name: swaggerapi/swagger-converter:v1.0.4
      alias: swagger-converter
  variables:
    AUTOREST_OUTPUT_FOLDER: ./packages/generated
    PACKAGE_PUBLISH: 'true'
    SWAGGER_CONVERT_API: http://swagger-converter:8080/api/convert
    SWAGGER_FILE_URL: https://finnhub.io/static/swagger.json
  before_script:
    - !reference [.email-notification, before_script]
    - npm install --location=global autorest semver
  script:
    - ./scripts/generate.sh
    - if [ ! -d $AUTOREST_OUTPUT_FOLDER ] && [ $? -eq 0 ]; then exit 0; fi
    # send out notification email
    - export PACKAGE_VERSION=$(jq -r '.version' ./packages/generated/package.json)
    - export MAILERSEND_SUBJECT="Package $PACKAGE_NAME ($PACKAGE_VERSION) has been published"
    - export MAILERSEND_TEMPLATE_ID="pq3enl6npd542vwr"
    - |
      export MAILERSEND_TEMPLATE_DATA='{
        "package_name": "'$PACKAGE_NAME'",
        "package_version": "'$PACKAGE_VERSION'",
        "pipeline_job_link": "'$CI_JOB_URL'",
        "project_link": "'$CI_PROJECT_URL'",
        "registry_link": "'$CI_PROJECT_URL/-/packages'"
      }'
    - !reference [.email-notification, script]
