# Cspell:disable

enableGlobalCache: false
nodeLinker: pnp

npmRegistries:
  //gitlab.com/api/v4/projects/56836135/packages/npm/:
    npmAlwaysAuth: true
    npmAuthToken: "${GITLAB_COM_LOGIN_TOKEN:-''}"

npmScopes:
  jeanmc:
    npmPublishRegistry: 'https://gitlab.com/api/v4/projects/56836135/packages/npm/'
    npmRegistryServer: 'https://gitlab.com/api/v4/projects/56836135/packages/npm/'

yarnPath: .yarn/releases/yarn-4.1.1.cjs
