enableGlobalCache: false

nodeLinker: pnp

npmScopes:
  jeanmc:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_AUTH_TOKEN:-''}"
    npmPublishRegistry: "https://registry.npmjs.org"
    npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@jeanmc/finnhub-sdk@*":
    dependencies:
      "@types/node": "*"
      builtin-modules: "*"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
