enableGlobalCache: false

nodeLinker: pnp

npmRegistries:
  //gitlab.com/api/v4/projects/56836135/packages/npm/:
    npmAlwaysAuth: true
    npmAuthToken: "${GITLAB_COM_LOGIN_TOKEN:-''}"

npmScopes:
  jeanmc:
    npmPublishRegistry: "https://gitlab.com/api/v4/projects/56836135/packages/npm/"
    npmRegistryServer: "https://gitlab.com/api/v4/projects/56836135/packages/npm/"

packageExtensions:
  "@jeanmc/finnhub-sdk@*":
    dependencies:
      "@types/node": "*"
      builtin-modules: "*"

yarnPath: .yarn/releases/yarn-4.5.3.cjs
