name: '@jeanmc/finnhub-sdk Package Publishing'
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master
jobs:
  publish-package:
    permissions: read-all
    runs-on: ubuntu-latest
    env:
      AUTOREST_OUTPUT_FOLDER: './packages/generated'
      PACKAGE_NAME: '@jeanmc/finnhub-sdk'
      PACKAGE_PUBLISH: "${{ github.event_name == 'schedule' && 'true' || 'false' }}"
      PACKAGE_TEST_BUILD: "${{ github.event_name == 'schedule' && 'false' || 'true' }}"
      SWAGGER_CONVERT_API: 'http://localhost:8080/api/convert'
      SWAGGER_FILE_URL: 'https://finnhub.io/static/swagger.json'
      YARN_ENABLE_IMMUTABLE_INSTALLS: 'false'
    services:
      swagger-converter:
        image: swaggerapi/swagger-converter:v1.0.5
        ports:
          - 8080:8080
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - run: npm install --location=global autorest semver
      - run: ./scripts/generate.sh
        env:
          NPM_AUTH_TOKEN: "${{ secrets.NPM_AUTH_TOKEN }}"
